CREATE TABLE "images" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "user_id" INTEGER REFERENCES users(id) ON DELETE SET NULL,
    "filename" varchar(255) NOT NULL,
    "orig_ext" varchar(5) NOT NULL,
    "created_at" timestamp DEFAULT (now())
);
