CREATE TABLE "albums" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" varchar(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT now(),
"updated_at" timestamp
);
