CREATE TABLE "albums" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "user_id" INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP DEFAULT now(),
    "updated_at" TIMESTAMP
);
