CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "is_admin" bool NOT NULL DEFAULT FALSE,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);
